name: Deploy PSQL

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to play"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HOST: root@46.161.52.147

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run external script
        run: |
          chmod +x ./create-network.sh
          bash ./create-network.sh      